# Используем официальный образ nginx
FROM nginx:latest

# Копируем файл index.html в директорию сервера nginx
COPY index.html /usr/share/nginx/html/index.html

# Открываем порт 80 для подключения
EXPOSE 80